// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owvotisngowqdiymdlce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93dm90aXNuZ293cWRpeW1kbGNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTIzMjQsImV4cCI6MjA2MzY4ODMyNH0.Z5vk8Jr-3XXmReTNRwFEHUPlXY9uxPKD2BXE9ol-DCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);